In [10]:
# library ---> کارهای خاص دستورات خاص
#pandas ----> csv , excel , جدول dataframe

import pandas as pd
df = pd.read_csv("spotify_songs.csv")
df

,track_id,track_name,Unnamed: 2,trtrack_artistack_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
0,6f807x0ima9a1j3VPbc7VN,I Don't Care (with Justin Bieber) - Loud Luxur...,Ed Sheeran,66,2oCs0DGTsRO98Gh5ZSl2Cx,I Don't Care (with Justin Bieber) [Loud Luxury...,2019-06-14,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,6,-2.634,1,0.0583,0.102000,0.000000,0.0653,0.5180,122.036,194754
1,0r7CVbZTWZgbTCYdfa2P31,Memories - Dillon Francis Remix,Maroon 5,67,63rPSO264uRjW1X5E6cWv6,Memories (Dillon Francis Remix),2019-12-13,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,11,-4.969,1,0.0373,0.072400,0.004210,0.3570,0.6930,99.972,162600
2,1z1Hg7Vb0AhHDiEmnDE79l,All the Time - Don Diablo Remix,Zara Larsson,70,1HoSmj2eLcsrR0vE9gThr4,All the Time (Don Diablo Remix),2019-07-05,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,1,-3.432,0,0.0742,0.079400,0.000023,0.1100,0.6130,124.008,176616
3,75FpbthrwQmzHlBJLuGdC7,Call You Mine - Keanu Silva Remix,The Chainsmokers,60,1nqYsOef1yKKuGOVchbsk6,Call You Mine - The Remixes,2019-07-19,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,7,-3.778,1,0.1020,0.028700,0.000009,0.2040,0.2770,121.956,169093
4,1e8PAfcKUYoKkxPhrHqw4x,Someone You Loved - Future Humans Remix,Lewis Capaldi,69,7m7vv9wlQ4i0LFuJiE2zsQ,Someone You Loved (Future Humans Remix),2019-03-05,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,1,-4.672,1,0.0359,0.080300,0.000000,0.0833,0.7250,123.976,189052
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32828,7bxnKAamR3snQ1VGLuVfC1,City Of Lights - Official Radio Edit,Lush & Simon,42,2azRoBBWEEEYhqV6sb7JrT,City Of Lights (Vocal Mix),2014-04-28,♥ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,...,2,-1.814,1,0.0936,0.076600,0.000000,0.0668,0.2100,128.170,204375
32829,5Aevni09Em4575077nkWHz,Closer - Sultan & Ned Shepard Remix,Tegan and Sara,20,6kD6KLxj7s8eCE3ABvAyf5,Closer Remixed,2013-03-08,♥ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,...,0,-4.462,1,0.0420,0.001710,0.004270,0.3750,0.4000,128.041,353120
32830,7ImMqPP3Q1yfUHvsdn7wEo,Sweet Surrender - Radio Edit,Starkillers,14,0ltWNSY9JgxoIZO4VzuCa6,Sweet Surrender (Radio Edit),2014-04-21,♥ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,...,6,-4.899,0,0.0481,0.108000,0.000001,0.1500,0.4360,127.989,210112
32831,2m69mhnfQ1Oq6lGtXuYhgX,Only For You - Maor Levi Remix,Mat Zo,15,1fGrOkHnHJcStl14zNx8Jy,Only For You (Remixes),2014-01-01,♥ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,...,2,-3.361,1,0.1090,0.007920,0.127000,0.3430,0.3080,128.008,367432
32832,29zWqhca3zt5NsckZqDf6c,Typhoon - Original Mix,Julian Calor,27,0X3mUOm6MhxR7PzxG95rAo,Typhoon/Storm,2014-03-03,♥ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,...,5,-4.571,0,0.0385,0.000133,0.341000,0.7420,0.0894,127.984,337500

def ---> کار مشخص ---> a + b = c

In [11]:
def spotify(top_n = 3): 
    artist = input("enter your favorite artist : ")
    genre = input("چه ژانری آهنگ گوش میدی :(pop , rap , edm , r&b , rock)")
    mood = input("چه مودی داری ( happy , sad , energetic , calm)")

    mood_dict ={
        'happy' : 'hapy' , 'energetic' : 'energetik' , 'happy' : 'شاد' 
        }
    
    mood = mood_dict.get(mood , mood)
    songs = df.copy()

    if artist : 
        #songs['Unnamed: 2'] ----> ستون ایم خواننده 
        #.str ----> تایپ ستون داده از جنس رشته یا string هست
        #.contain ----> شامل شدن
        # case : روی حروف کوچک یا بزرگ حساس adele or ADele
        # regex : amir - *amir - #amir - @amir ---> off
        songs = songs[songs['Unnamed: 2'].str.contains(artist , case = False , na = False , regex = False )]

    if genre : 
        songs = songs[songs['playlist_genre'].str.contains(genre , case = False , na = False , regex = False )]

    if mood == 'happy' :
        songs = songs[songs['valence'] > 0.7]

    elif mood == 'sad' : 
        songs = songs[songs['valence'] < 0.4]
    
    elif mood == 'calm':
        if 'energy' in songs.columns:
            songs = songs[(songs['valence'].between(0.4 , 0.7 , inclusive= 'both')) & (songs['energy'] < 0.4)]
        else : 
            songs = songs[songs['energy'] < 0.4]

    elif mood == 'energetic' : 
        if 'energy' in songs.columns : 
            songs = songs[songs['energy'] > 0.5]
        else : 
            songs = songs[songs['valence'] > 0.5]

    
    elif songs.empty : 
        print(" music not found ....")

    return songs.head(3)

In [12]:
spotify(top_n = 3)

,track_id,track_name,Unnamed: 2,trtrack_artistack_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
5511,7FIWs0pqAYbP91WWM0vlTQ,Godzilla (feat. Juice WRLD),Eminem,79,4otkd9As6YaxxEkIjXPiZ6,Music To Be Murdered By,2020-01-17,RapCaviar,37i9dQZF1DX0XUsuxWHRQd,rap,...,10,-5.260,0,0.342,0.14500,0.000000,0.292,0.8290,165.995,210800
5516,1lO9CZo6eDrOy0S7khgryG,No Regrets (feat. Don Toliver),Eminem,71,4otkd9As6YaxxEkIjXPiZ6,Music To Be Murdered By,2020-01-17,RapCaviar,37i9dQZF1DX0XUsuxWHRQd,rap,...,9,-5.407,1,0.046,0.00480,0.005360,0.588,0.0687,134.935,200947
5926,5SiZJoLXp3WOl3J4C8IK0d,Darkness,Eminem,75,4otkd9As6YaxxEkIjXPiZ6,Music To Be Murdered By,2020-01-17,Hip-Hop Central,37i9dQZF1DWY6tYEFs22tT,rap,...,2,-7.161,1,0.308,0.00998,0.000008,0.643,0.1950,75.055,337147

tamrin : 

- تمام پروژه ها و مباحث جلسات قبل مرور بشه و هر سوالی تو هر بخشی داشتی ازم بپرس راهنمایی کنم

tamrin :

- یه فست فودی 
- username
- چی می خوای سفارش بدی ---> dictionary ذخیره بشه 
- شماره تماس 
- ادرس 


delivery : {
    user1 : {"name":"amirali , "order" : "pizza" , "count" : 3 , "phone": 0912123456} , 


}