In [6]:
import numpy as np
import pandas as pd
np.random.seed(42)
num_samples = 100000


data = {
    #دما
    'temperature' : np.random.normal(loc=30 , scale= 5 , size = num_samples),
    #میزان بارش
    'precipitation' : np.random.normal(loc = 500 , scale= 100 , size = num_samples),
    #رطوبت
    'humidity': np.random.normal(loc=50 , scale= 10 , size = num_samples),
    'water_level':np.random.uniform(0,100,size=num_samples),
    'cultivated_area':np.random.uniform(0.1,0.9,size=num_samples)
}

df = pd.DataFrame(data)
df

       temperature  precipitation   humidity  water_level  cultivated_area
0        32.483571     603.059459  65.618407    60.357601         0.287875
1        29.308678     384.464523  49.057717    23.533786         0.120681
2        33.238443     557.543719  36.704644     5.082917         0.482341
3        37.615149     438.076154  36.113619    30.850741         0.834582
4        28.829233     467.259719  46.573492    90.973857         0.413101
...            ...            ...        ...          ...              ...
99995    28.873875     373.545174  45.676856    16.486876         0.176423
99996    27.151112     556.565416  43.125341    68.091404         0.547492
99997    32.045925     516.001996  43.203619    67.337808         0.615047
99998    28.944542     585.567309  39.279082    81.389783         0.823605
99999    30.600315     393.505203  46.421538     9.719892         0.724169

[100000 rows x 5 columns]

In [7]:
def risk(row):
    if row['temperature'] > 30 and row['precipitation'] < 200 and row['water_level'] < 0.2 :
        return 2 #پرخطر
    elif row['temperature'] > 30 or row['precipitation'] < 200 : 
        return 1 #کم خطر
    else : 
        return 0 #بدون خطر

In [8]:
df['risk'] = df.apply(risk , axis = 1)

In [9]:
df

,temperature,precipitation,humidity,water_level,cultivated_area,risk
0,32.483571,603.059459,65.618407,60.357601,0.287875,1
1,29.308678,384.464523,49.057717,23.533786,0.120681,0
2,33.238443,557.543719,36.704644,5.082917,0.482341,1
3,37.615149,438.076154,36.113619,30.850741,0.834582,1
4,28.829233,467.259719,46.573492,90.973857,0.413101,0
...,...,...,...,...,...,...
99995,28.873875,373.545174,45.676856,16.486876,0.176423,0
99996,27.151112,556.565416,43.125341,68.091404,0.547492,0
99997,32.045925,516.001996,43.203619,67.337808,0.615047,1
99998,28.944542,585.567309,39.279082,81.389783,0.823605,0
99999,30.600315,393.505203,46.421538,9.719892,0.724169,1

In [12]:
x=df.drop('risk',axis=1)
y=df['risk']

In [13]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test=train_test_split(x,y,test_size=0.2)

In [14]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators = 150)
model.fit(x_train , y_train)
from sklearn.metrics import accuracy_score
y_pred=model.predict(x_test)
acc=accuracy_score(y_pred,y_test)

In [15]:
print (acc)

1.0